//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "competition")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub date: Date,
    pub location: String,
    pub r#type: String,
    pub host: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::swim_time::Entity")]
    SwimTime,
    #[sea_orm(
        belongs_to = "super::team::Entity",
        from = "Column::Host",
        to = "super::team::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Team,
}

impl Related<super::swim_time::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SwimTime.def()
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Team.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
