//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.11

pub use super::competition::Entity as Competition;
pub use super::swim_time::Entity as SwimTime;
pub use super::swimmer::Entity as Swimmer;
pub use super::team::Entity as Team;
